language: android

env:
  global:
    - ANDROID_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=23.0.2
    - ANDROID_ABI=google_apis/armeabi-v7a

android:
    components:
        - platform-tools
        - tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_API_LEVEL


      # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-$ANDROID_API_LEVEL
        - sys-img-armeabi-v7a-addon-google_apis-google-21

notifications:
  email: false

before_install:
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:"$ANDROID_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - ./scripts/wait_for_emulator.sh
  - adb shell input keyevent 82 &