language: android

env:
  global:
    - ANDROID_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=21.1.2
    - ANDROID_ABI=google_apis/armeabi-v7a

android:
    components:
        - platform-tools
        - tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_API_LEVEL


      # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-$ANDROID_API_LEVEL
        - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL

branches:
  except:
    - master

notifications:
   email:
     - sam.thngo+maddj-travis-ci@gmail.com

before_install:
  # We can also do 'git update-index --chmod=+x gradlew' in the git repository
  - chmod +x gradlew
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:21" --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - ./scripts/wait_for_emulator.sh
  - adb shell input keyevent 82 &