language: android
jdk: oraclejdk7

# Turn off caching to avoid any caching problems
cache: false

# Use the Travis Container-Based Infrastructure (see #203)
sudo: false

env:
  global:
    - ANDROID_API_LEVEL=23
    - ANDROID_BUILD_TOOLS_VERSION=23.0.1
    # - ANDROID_ABI=google_apis/armeabi-v7a
    - ANDROID_ABI=google_apis/x86_64
    - ADB_INSTALL_TIMEOUT=15

android:
    components:
        - platform-tools
        - tools
        - build-tools-$ANDROID_BUILD_TOOLS_VERSION
        - android-$ANDROID_API_LEVEL


      # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository
        - addon-google_apis-google-$ANDROID_API_LEVEL
        # - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
        - sys-img-x86_64-addon-google_apis-google-$ANDROID_API_LEVEL

branches:
  except:
    - master

notifications:
   email:
     - sam.thngo+maddj-travis-ci@gmail.com

before_install:
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:23" --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - ./scripts/wait_for_emulator.sh
  - adb shell input keyevent 82 &